---
# tasks file for ansible-metsflask

- name: "Ensure python3-venv is installed (Ubuntu)"
  apt:
    name: "python3-venv"
    state: "present"
  when: ansible_os_family == 'Debian'

- name: Create metsflask group
  group:
    name: "metsflask"
    system: yes

- name: Create metsflask user
  user: 
    name: "metsflask"
    home: "/opt/metsflask"
    create_home: "no"
    shell: "/bin/false"
    system: yes
    group: "metsflask"

- name: Create base directory for the application
  file:
    path: "/opt/metsflask"
    state: directory

- name: Clone metsflask repository
  git:
    repo: "https://github.com/tw4l/METSFlask"
    dest: "/opt/metsflask/src"
    version: "main"

- name: Create virtualenv
  pip:
    chdir: "/opt/metsflask/src"
    requirements: "requirements.txt"
    virtualenv: "/opt/metsflask/venv"
    virtualenv_command: "/usr/bin/python3 -m venv"

- name: Change permissions for application directories
  file:
    path: "/opt/metsflask"
    state: directory
    recurse: yes
    owner: metsflask
    group: metsflask

- name: Create systemd config file
  template:
    src: "etc/systemd/system/metsflask.service"
    dest: "/etc/systemd/system/metsflask.service"

- name: Initialize database
  command:
    cmd: "/opt/metsflask/venv/bin/python3 db_create.py"
    chdir: "/opt/metsflask/src"
  become: yes
  become_user: metsflask
  when: metsflask_initdb | bool
  tags: metsflask-initdb

- name: "Enable service"
  systemd:
    name: "metsflask"
    state: "started"
    enabled: "yes"
    daemon_reload: "yes"
